version: '3.3'
services:
  pauls-fund:
#    build: .
    image: docker.io/kamau01/pauls-fund:latest
    container_name: pauls
    ports:
      - "8080:8080"
      - "443:8080"
      # - "80:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "jdbc:postgresql:pf_db?user=postgres&password=12345"
      HOST: db
      DB_PORT: 5432
      DB_NAME: pf_db
      DB_USER: postgres
      DB_PASSWORD: 12345
    stdin_open: true
    mem_limit: 350M
    tty: true
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pf_db
    ports:
      - "5432:5432"
    mem_limit: 200M
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: chegeizoh50@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "80:80"
    mem_limit: 200M
    links:
      - db
    depends_on:
      - db
